version: "3.5"
services:
  sentry:
    build:
      context: sentry
      args:
        UPSTREAM_VERSION: v0.0.70
    restart: unless-stopped
    environment:
      - CONTRIBUTOOR_USERNAME
      - CONTRIBUTOOR_PASSWORD
      - CONTRIBUTOOR_ATTESTATION_CONTRIBUTION
